### ISSUE TITLE
examples test failed

### ISSUE THREAD

**Issue by absentmindid** [akaszynski/pymeshfix#4]
Hi,
I use the test code in introduction parts:
to use example.native()
error:
/usr/bin/python3.6 /home/absarthas/PycharmProjects/pymeshfixtest/testcode.py
Traceback (most recent call last):
  File "/home/absarthas/PycharmProjects/pymeshfixtest/testcode.py", line 5, in <module>
    examples.native()
  File "/home/absarthas/.local/lib/python3.6/site-packages/pymeshfix/examples/fix.py", line 12, in native
    pymeshfix._meshfix.CleanFromFile(bunny_scan, outfile)
AttributeError: module 'pymeshfix._meshfix' has no attribute 'CleanFromFile'

if use examples.with_vtk()
error:
/usr/bin/python3.6 /home/absarthas/PycharmProjects/pymeshfixtest/testcode.py
Plotting input mesh
Traceback (most recent call last):
  File "/home/absarthas/PycharmProjects/pymeshfixtest/testcode.py", line 8, in <module>
    examples.with_vtk()
  File "/home/absarthas/.local/lib/python3.6/site-packages/pymeshfix/examples/fix.py", line 21, in with_vtk
    meshfix.Plot()
AttributeError: 'MeshFix' object has no attribute 'Plot'

Would you please help me resolve this problem?
the platform is ubuntu 18.04, python 3.6

Thank you!!
Bowen

**Comment by akaszynski** [comment]
Sorry, it needs to be updated.  Should be “plot”.

**Comment by akaszynski** [comment]
Fixed in ``pymeshfix==0.12.4``.

**Comment by absentmindid** [comment]
Thank you!
